### ISSUE TITLE
按照文档在vue2中引入使用报错

### ISSUE THREAD

**Issue by WSCZou** [xpyjs/gantt-vue2#4]
报错信息：Typeerror cannot read property of null (reading 'setupContext')

**Comment by jeremyjone** [comment]
请使用 vue 2.6.14 版本。 vue 2.7 版本对 @vue/composition-api 做了调整

**Comment by WSCZou** [comment]
我的vue版本是2.6.14 但还是报这个错

**Comment by jeremyjone** [comment]
2.6.14 不会再报该错误，它是因为 2.6.x 与 2.7 冲突导致
