### ISSUE TITLE
按文档正常引入严重报错

### ISSUE THREAD

**Issue by beierzhijin** [xpyjs/gantt-vue2#5]
`"vue": "2.6.14",` `"@xpyjs/gantt-vue2": "^1.0.1",`
![image](https://user-images.githubusercontent.com/54610243/190325143-dd234c71-6b10-44b6-a5ec-126278cf504c.png)

**Comment by jeremyjone** [comment]
具体代码

**Comment by jxh-0514** [comment]
我现在也是这样报错
<template>
  <div>
    
    <x-gantt data-index="index" :data="dataList">
      
      <x-gantt-column label="index" />
    </x-gantt>
  </div>
</template>

<script>
import Vue from "vue";
import XGantt from "@xpyjs/gantt-vue2";
import "@xpyjs/gantt-vue2/lib/index.css";

Vue.use(XGantt);
export default {
  components: {},

  data() {
    return {
      dataList: [
        {
          index: 1,
          startDate: "2020-06-05",
          endDate: "2020-08-20",
          ttt: {
            a: "aaa",
            b: "bbb",
          },
          name: "mydata1",
          children: [], // children 是必须的，如果没有，给一个空数组即可
        },
        {
          index: 2,
          startDate: "2020-07-07",
          endDate: "2020-09-11",
          ttt: {},
          name: "mydata2",
          children: [
            {
              index: 3,
              startDate: "2020-07-10",
              endDate: "2020-08-15",
              ttt: {
                a: "aaa",
              },
              name: "child1",
              children: [], // children 是必须的，如果没有，给一个空数组即可
            },
          ],
        },
      ],
    };
  },

  computed: {},

  watch: {},

  destroyed() {},

  //生命周期 - 创建完成（可以访问当前this实例）
  created() {},
  //生命周期 - 挂载完成（可以访问DOM元素）
  mounted() {},

  methods: {},
};
</script>
<style lang="scss" scoped></style>

> 具体代码

**Comment by jeremyjone** [comment]
已更新至 v1.0.3

同时，要确保项目使用 v2.7 以下版本的 `vue` 以及 `vue-template-compiler`，如图：

![image](https://user-images.githubusercontent.com/37676231/202496414-e3912559-5c67-4d14-ac98-02659d87da7b.png)

如果版本号前面有 `^`，请去掉。

**原因：**
默认安装 2.7+版本，与当前版本有冲突。
