### ISSUE TITLE
vue2引入报错，已固定版本

### ISSUE THREAD

**Issue by zhouhexiang12** [xpyjs/gantt-vue2#6]
![image](https://user-images.githubusercontent.com/42677027/210475411-6a1a3e3f-d5fe-40da-bf4d-953c746923d1.png)

**Comment by zhouhexiang12** [comment]
./node_modules/@xpyjs/gantt-vue2/lib/index.umd.min.js 15:21160
Module parse failed: Unexpected token (15:21160)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
| PERFORMANCE OF THIS SOFTWARE.
> *****************************************************************************

**Comment by jeremyjone** [comment]
how？

**Comment by karlbin** [comment]
引入依旧报这个错误，请问如何解决？整体脚手架是ruoyi，引入本gantt启动失败，报如上同样的错误。

<img width="590" alt="企业微信截图_16759968909159" src="https://user-images.githubusercontent.com/11063054/217986910-aaf448d1-0dd6-4cb5-96be-2cca82ecd034.png">
改为非压缩文件后能看到具体的报错信息如上

**Comment by jeremyjone** [comment]
> 引入依旧报这个错误，请问如何解决？整体脚手架是ruoyi，引入本gantt启动失败，报如上同样的错误。
> 
> <img alt="企业微信截图_16759968909159" width="590" src="https://user-images.githubusercontent.com/11063054/217986910-aaf448d1-0dd6-4cb5-96be-2cca82ecd034.png">
> 
> 改为非压缩文件后能看到具体的报错信息如上

@karlbin 这是缺 js 语法插件啊，`??` 是 `ES2020` 的新特性，试一下 `@babel/plugin-proposal-nullish-coalescing-operator`，或者直接升级 babel 版本
