### ISSUE TITLE
expand-all属性没有效果

### ISSUE THREAD

**Issue by Aescde** [xpyjs/gantt-vue2#8]
问题出现在src/models/data/row.ts文件158行的方法中
`  
initData(data: any, options: DataOptions) {
const sl = options.startLabel || Variables.key.start;
    const el = options.endLabel || Variables.key.end;
    Object.assign(this.options, { sl, el });
    this.__isExpand = this.options.isExpand || true;
  }`
其中this.options.isExpand为undefined 导致无论属性如何设置结果都为true
可将代码修改成`Object.assign(this.options, { sl, el,isExpand:options.isExpand  });
    this.__isExpand = this.options.isExpand ?? true;`

**Comment by xpyjs** [comment]
你说得对~谢谢。我已改，update to v2.0.2
