### ISSUE TITLE
expand-all 生效问题反馈

### ISSUE THREAD

**Issue by Aescde** [xpyjs/gantt-vue2#9]
感谢作者还有时间运维一个很早之前的项目！
这次更新并没有解决expand-all属性生效的问题
可能是我之前的答复对您产生了误导
以下是对这块代码详细的注释 应该能帮助你找到对应的问题
![code](https://github.com/xpyjs/gantt-vue2/assets/76914699/0d8326b4-d519-402e-a271-f9d0779ace47)

**Comment by jeremyjone** [comment]
要不然你直接pr吧🤣我确实好久没看这个项目了，最近没时间看，我直接按你说的改了一下

**Comment by jeremyjone** [comment]
update to v2.0.3
